name: Deploy via ftp
on:
  pull_request:
    branches:
      ['develop']
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.
    - name: run install, build
      run: |
        npm install
        npm run build

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ftp.codetreino.com.br
        user: codetreino1
        password: Codetreino2024@
        localDir: "dist/code-treino-v3/browser"
